### ISSUE TITLE
SSB Data

### ISSUE THREAD

**Issue by mdmazur** [jerellejesse/HCR-shiny#1]
I'm not sure if the SSB data for a specific scenario is from the right scenario. The SSB data from OM Scenario 1, Rho Scenario 2, Frequency Scenario 1, and HCR Scenario 1 seems off. 
[Table.csv](https://github.com/jerellejesse/HCR-shiny/files/6985291/Table.csv)

**Comment by jerellejesse** [comment]
I will check into this!

**Comment by jerellejesse** [comment]
I have the right scenario 1 now! Trajectory, Mohns rho, and %REE plots fixed. Just need to pull the data for the confidence interval plots tomorrow.

**Comment by jerellejesse** [comment]
Fixed- trajectory, confidence interval, rho, %ree plots
