### ISSUE TITLE
Kobe boxes on comparison tab

### ISSUE THREAD

**Issue by jerellejesse** [jerellejesse/HCR-shiny#10]
Colored boxes for kobe plot not showing on comparison plots only. Something to do with maxSSBest and maxF?

**Comment by mdmazur** [comment]
Does this still happen when the Kobe plot is for the 'true' stock status?

**Comment by jerellejesse** [comment]
Is the "true" plot code just the Kobe_plot.R in the groundfish MSE? I don't think I have the data pulled for that yet, and when I tried with the kobeDataCode.R that you just helped me with I got an error. I can look into it more, that was just quickly trying it.

**Comment by jerellejesse** [comment]
I got the colored boxes figured out! I wasn't sure if we wanted the true kobe plots or just the estimated ones on the management tab?

**Comment by mdmazur** [comment]
I think if anything we should have the true Kobe plots. The kobeDataCode.R will need to be modified to pull the data that the Kobe_plot.R in the groundfish MSE is pulling. In this case, we don't have to worry about the timing since the OM values in all scenarios go to 2040.
